feat(bash): Add checksum function

diff --git a/bash/bash_functions b/bash/bash_functions
--- a/bash/bash_functions
+++ b/bash/bash_functions
@@ -1,3 +1,23 @@
 column_names () {
 	head -1 $1 | tr , '\n' | cat -n
 }
+
+function checksum() {
+  local s
+  s=$(curl -fsSL "$1")
+  local h
+  if command -v shasum >/dev/null ; then
+    h=shasum
+  else
+    h=sha1sum
+  fi
+  if [ ! "$2" ] ; then
+    printf %s\\n "$s" | "$h" | awk '{print $1}'
+    return 1;
+  fi
+  printf %s\\n "$s" | "$h" --check --status <(printf '%s  -\n' "$2") || {
+    echo "checksum failed" >&2;
+    return 1;
+  }
+  printf %s\\n "$s"
+}
